ARITHMETIC FUNCTION

np.min(x)
np.max(x)
np.argmin(x)
np.sqrt(x)
np.sin(x)
np.cos(x)
np.cumsum(x)

In [1]:
import numpy as np

In [6]:
var = np.array([9,5,6,1,2,3,4])

print("min :",np.min(var),np.argmin(var)) #argmin index find
print("max :",np.max(var),np.argmin(var))

min : 1 3
max : 9 3


In [9]:
var1 = np.array([[2,1,3],[3,5,7]])
print(np.min(var1,axis=0)) #axis = 0(columns wise)

[2 1 3]


In [11]:
var = np.array([9,5,6,1,2,3,4])

print("min :",np.min(var),np.argmin(var)) #argmin index find
print("max :",np.max(var),np.argmin(var))
print("sqrt :",np.sqrt(var))

min : 1 3
max : 9 3
sqrt : [3.         2.23606798 2.44948974 1.         1.41421356 1.73205081
 2.        ]


In [13]:
var2 = np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]


In [14]:
var2 = np.array([1,2,3])
print(np.cumsum(var2))

[1 3 6]
