# a+b = np.add(a,b)
# a-b = np.subtract(a,b)
# a*b = np.multiply
# a/b = np.divide(a,b)
# a%b = np.mod(a,b)
# a**b = np.power(a,b)
# 1/a = np.reciprocal(a)


In [2]:
import numpy as np

In [3]:
var = np.array([1,2,3,4])
var_add = var + 3
print(var_add)

[4 5 6 7]


In [4]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_add = var1 + var2

print(var_add)

[2 4 6 8]


In [5]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_add = var1 - var2

print(var_add)

[0 0 0 0]


In [6]:
var = np.array([1,2,3,4])
var_add = var - 3
print(var_add)

[-2 -1  0  1]


In [7]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_add = var1 * var2

print(var_add)

[ 1  4  9 16]


In [8]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_add = var1 / var2

print(var_add)

[1. 1. 1. 1.]


In [10]:
var1 = np.array([4,5,6,7])
var2 = np.array([1,2,3,4])
var_add = var1 % var2

print(var_add)

[0 1 0 3]


In [11]:
var = np.array([1,2,3,4])
var_add = var / 3
print(var_add)

[0.33333333 0.66666667 1.         1.33333333]


In [12]:
var = np.array([1,2,3,4])
var_add = var % 3
print(var_add)

[1 2 0 1]


In [14]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
var_add = np.add(var1,var2)

print(var_add)

[2 4 6 8]


######   2D ARRAY ########

In [16]:
var_1 = np.array([[1,2,3,4],[1,2,3,4]])
var_2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var_1)
print(var_2)
print()
var_add2 = var_1 +var_2

print(var_add2)

[[1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [17]:
var11 = np.array([1,2,3,4])
reci =np.reciprocal(var)

print(reci)

[1 0 0 0]
