In [4]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([3])
print(np.power(var1,var2))



[ 1  8 27 64]


In [7]:
var1 = np.array([ 1,8,27,64])
print(np.sqrt(var1))


[1.         2.82842712 5.19615242 8.        ]


In [8]:
a = [30,40,50]
b = [4,4,4]
print(a+b)

[30, 40, 50, 4, 4, 4]


#Concatentate

In [10]:
var3 = np.array([1,2,3,4])
var4 = np.array([3,4,5,5])
print(np.concatenate([var3,var4]))

[1 2 3 4 3 4 5 5]


In [11]:
print(np.concatenate([var3,var4],axis=0))

[1 2 3 4 3 4 5 5]


In [12]:
var3 = np.array([1,2],[3,4])
var4 = np.array([3,4],[5,5])
print(np.concatenate([var3,var4]))

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [13]:
print(np.hstack([var3,var4])) # horizontal 

[1 2 3 4 3 4 5 5]


In [14]:
print(np.vstack([var3,var4]))#vertical

[[1 2 3 4]
 [3 4 5 5]]


In [16]:
a = np.array([2,3,4,5,6,7,8,9])
print(np.array_split(a,3))
print(b[1])
      
          

[array([2, 3, 4]), array([5, 6, 7]), array([8, 9])]
4


In [20]:
a = np.array([[2,3,4,5],[6,7,8,9]])
print(np.array_split(a,3))
print(b)
      
          

[array([[2, 3, 4, 5]]), array([[6, 7, 8, 9]]), array([], shape=(0, 4), dtype=int64)]
[4, 4, 4]


# FUNCTION

# np.append(,g) = Append items to an array
# np.insert(a,1,5) = Insert items in an array
# np.delete(a,[1] = Delete items from an array

In [21]:
d = np.array([2,3,4,5,6,7,8,9])
print(np.append(d,10))

[ 2  3  4  5  6  7  8  9 10]


In [22]:
d = np.array([[2,3,4,5],[6,7,8,9]])
print(np.append(d,[11,12]))

[ 2  3  4  5  6  7  8  9 11 12]


In [23]:
print(np.insert(a,1,50)) # (array,index,valuePut)

[ 2 50  3  4  5  6  7  8  9]


In [25]:
d = np.array([[2,3,4,5],[6,7,8,9]])
print(np.insert(d,1,[11,12],axis = 1))

[[ 2 11  3  4  5]
 [ 6 12  7  8  9]]


In [27]:
print(d)
print(np.delete(d,1))

[[2 3 4 5]
 [6 7 8 9]]
[2 4 5 6 7 8 9]
