In [4]:
import numpy as np
arr = np.array([[13,140,13],[1,2,3]])
print(arr)

[[ 13 140  13]
 [  1   2   3]]


In [5]:
np.size(arr)

6

# Array type

In [9]:
arr1 = np.array([1,2,3])
arr2 = np.array([[13,140,13],[1,2,3]])
arr3 = np.array([[[13,140,13],[4,5,6],[1,2,3]]])

print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
2
3


# DataType

In [12]:
arr = np.array([1,2,3.3])
print(arr.dtype)

float64


# Datatype change to another datatype


# astype()

In [15]:
arr = np.array([1,2,3.3])
print(arr)
print(arr.astype(int))


[1.  2.  3.3]
[1 2 3]
