In [1]:
import numpy as np

In [2]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
print(var1+var2)

[2 4 6 8]


In [4]:
var1 = np.array([1,2,3,4])
print(var1.shape)
print(var1)
var2 = np.array([[1],[2],[3]])
print(var2.shape)
print(var2)
print(var1+var2)

(4,)
[1 2 3 4]
(3, 1)
[[1]
 [2]
 [3]]
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
