In [4]:
python_list = [1,2,3,4,5]
print(python_list)
%timeit

[1, 2, 3, 4, 5]


In [5]:
# PYTHON(list)
%timeit [i**4 for i in range(1,9)]
#%timeit :- Its check the time of program run

233 ns ± 3.97 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [7]:
import numpy as np
%timeit np.arange(1,9)**4
 

797 ns ± 1.85 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [8]:
matrix = np.array([[2,3,4],[6,7,8]])
print(matrix)

[[2 3 4]
 [6 7 8]]


# Creating array from python lists


In [10]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


# With default value

In [11]:
# np.zeros(shape) 

zeros_array = np.zeros(3)
print(zeros_array)

[0. 0. 0.]


# Ones (shape)

In [12]:
ones_array = np.ones((2,3))
print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]]


#Full function(shape,value)

In [14]:
filled_array = np.full((2,2),8)# (shape,value 8)
print(filled_array)

[[8 8]
 [8 8]]


# Creating sequences of numbers in numpy

In [15]:
# arange
#(arange(start,stop,step)
# use of sequence or table

In [16]:
arr = np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [19]:
arr = np.arange(13,140,13)
print(arr)

[ 13  26  39  52  65  78  91 104 117 130]


# Creating identity matrices

In [20]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
