In [1]:
#rand():-The functin is used to generate a random value between 0 to 1

#random():-The function is used to generate a random value close to zero.
#This may return positive or negatjve number as well

#ranf() :-The function for doing random sampling in numpy.It return an array of 
# - specified shape and fills it with random floats in the halfopen interval [0.0,1.0]

#randint() :-The functin is used to generate a random number 

In [2]:
##### RANDOM ####

In [3]:
###### Rand() ####

In [4]:
import numpy as np


In [6]:
var = np.random.rand(4)
print(var)
#[0.41022768 0.35639296 0.54226673 0.35202208]

[0.79000351 0.52907278 0.39552476 0.60383984]


In [7]:
var1 = np.random.rand(2,5)
print(var1)

[[0.61564614 0.60415543 0.90543117 0.11769954 0.43591   ]
 [0.04742158 0.14235516 0.23715444 0.88908785 0.33363759]]


In [8]:
###### randn() ######

In [9]:
var2 = np.random.randn(4)
print(var2)

[ 0.20770479 -0.28433068 -1.75833288  1.20925348]


In [10]:
######## ranf()  #######

In [11]:
var3 = np.random.ranf(4)
print(var3)

[0.6600585  0.74961017 0.88673408 0.3184677 ]


In [12]:
 ######  randint().  ######

In [13]:
var4 = np.random.randint(5,20,5) #(min,max,total_values)
print(var4)

[11 17 18 12  7]
