In [1]:
import numpy as np

In [2]:
var = np.array([1,2,3,4])
print("Data Type :",var.dtype)

Data Type : int64


In [3]:
var = np.array([1.0,2.2,3.4,5.6])
print("Data Type :",var.dtype)

Data Type : float64


In [5]:
var = np.array(["A","B",1,2,3])
print("Data Type :",var.dtype)

Data Type : <U21


In [10]:
# List of characters that used to represent dtype in numpy
# i = integer
# b = boolean
# u = unsigned
# f = float
# c = complex float
# m = timedalta
# o = object
# s = string
# u = unicode string
# v = the fixed chunk of memory for other types(void)
#

In [12]:
x = np.array([1,2,3,4])
print("Data Type :",x.dtype)

Data Type : int64


In [14]:
x = np.array([1,2,3,4],dtype = np.int8)
print("Data Type :",x.dtype)
print(x)

Data Type : int8
[1 2 3 4]


In [15]:
x1 = np.array([1,2,3,4],dtype = "f")
print("Data Type :",x1.dtype)
print(x1)

Data Type : float32
[1. 2. 3. 4.]


In [17]:
x2 = np.array([1,2,3,4])
new = np.float32(x2)
new_one = np.int_(new)
print("Data Type :",x2.dtype)
print("Data Type :",new.dtype)
print("Data Type :",new_one.dtype)
print(x2)
print(new)
print(new_one)

Data Type : int64
Data Type : float32
Data Type : int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [18]:
x3 = np.array([1,2,3,4])
new_1=x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]
