INDEXING & SLICING

In [1]:
import numpy as np

In [3]:
var = np.array([9,8,7,6])
#.              0,1,2,3
#.             -4,-3,-2,-1
print(var[1])
print(var[-3])

8
8


In [6]:
var1 = np.array([[9,8,7],[4,3,2]])
print(var1)
print(var1.ndim)
print()
print(var1[0,2])


[[9 8 7]
 [4 3 2]]
2

7


In [8]:
var2 = np.array([[[1,2],[1,2]]])
print(var2)
print(var2.ndim)
print(var2[0,1])

[[[1 2]
  [1 2]]]
3
[1 2]


SLICING

In [9]:
#star:stop:step

In [13]:
x = np.array([1,2,3,4,5,6,7])
print(x)
print()
print("2 to 5 :",x[1:5])
print("2 to end :",x[1:])
print("stop :",x[::2])

[1 2 3 4 5 6 7]

2 to 5 : [2 3 4 5]
2 to end : [2 3 4 5 6 7]
stop : [1 3 5 7]


In [16]:
x1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(x1)
print()
print("8 to 5 :",x1[2,1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

8 to 5 : [12 13 14 15]
