In [1]:
import numpy as np

In [3]:
a = [[10,20,30],[40,50,60]]
arr = np.array(a)
print(arr)
print(arr.shape) # Row columns

[[10 20 30]
 [40 50 60]]
(2, 3)


In [4]:
print(len(arr)) #length

2


In [5]:
print(np.size(arr))

6


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
print(arr.dtype)#datatype of variable

int64


In [8]:
print(arr.astype(float))

[[10. 20. 30.]
 [40. 50. 60.]]


In [9]:
print(arr.astype(str))

[['10' '20' '30']
 ['40' '50' '60']]


In [10]:
print(arr.astype(int))

[[10 20 30]
 [40 50 60]]
