ITERATING NUMPY ARRAY

In [1]:
import numpy as np

In [2]:
var = np.array([1,2,3,4,5,6,7,8])
print(var)
print()
for i in var:
    print(i)

[1 2 3 4 5 6 7 8]

1
2
3
4
5
6
7
8


In [3]:
var1 = np.array([[1,2,3,4],[5,6,7,8]])
print(var1)
print()
for j in var1:
    print(j)
for k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]
[5 6 7 8]
1
2
3
4
5
6
7
8


In [4]:
x = np.array([[[1,2,3,4],[1,2,3,4]]])
print(x)
print(x.ndim)
print()
for i in x:
    for j in i:
        for k in j:
            print(k)


[[[1 2 3 4]
  [1 2 3 4]]]
3

1
2
3
4
1
2
3
4


In [5]:
 x2 = np.array([[[1,2,3,4],[5,6,7,8]]])
print(x2)
print(x2.ndim)
print()

for i in np.nditer(x2,flags=["buufered"],op_dtype = ["s"]):
    print(i)

[[[1 2 3 4]
  [5 6 7 8]]]
3



ValueError: Unexpected iterator global flag "buufered"