In [4]:
import numpy as np

x = np.array([1,2,3,4,5])
#ARRAY
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
y=[1,2,3,4,5]
#List
print(y)
print(type(y))

[1, 2, 3, 4, 5]
<class 'list'>


In [6]:
####################################


In [7]:
#Check timing in python(list) and NumPy(Array)


In [9]:
# PYTHON(list)
%timeit [i**4 for i in range(1,9)]
#%timeit :- Its check the time of program run

227 ns ± 2.82 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [11]:
import numpy as np
%timeit np.arange(1,9)**4
 

797 ns ± 18.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
#####################.    ARRAY.      #################

In [22]:
import numpy as np

x = [1,2,3,4]

y = np.array(x)

y #y define the type

print(type(y))
print(y.ndim) #y.dim is describle the dimensional 

<class 'numpy.ndarray'>
1


In [19]:
l = []

for i in range(1,5):
    #int_1 = input("Enter : ")# String dega
    int_1 = int(input("Enter : "))#Array
    l.append(int_1)
print(np.array(l))

Enter :  4
Enter :  5
Enter :  6
Enter :  7
Enter :  8
Enter :  8
Enter :  9
Enter :  4


[5 7 8 4]


In [ ]:
# 1-D Array -> [1 2 3 4 ] one square bracket
# 2-D Array -> [[1 2 3 4]] two square bracket
# 3-D Array -> [[[1 2 3 4]]] three square bracket
#Higher Dimensional Array



In [24]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]]) # Both array data same (number ) another error
print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [25]:
arr3 = np.array([[[1,2,3,4],[5,6,7,8],[11,12,13,14]]])
print(arr3)
print(arr3.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [11 12 13 14]]]
3


In [26]:
arrn = np.array([1,2,3,4],ndmin=10) #ndim is describle to number of array (10) dimensional
print(arrn)
print(arrn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
