In [1]:
import numpy as np

In [4]:
a = np.array([1,23,4])
b = np.array([4])
print(a)
print(b)

print(a*b)

[ 1 23  4]
[4]
[ 4 92 16]


In [9]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0:2,0:2])

[[10 20]
 [50 60]]


In [10]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0:3,0:3])

[[10 20 30]
 [50 60 70]]


In [11]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0,1:3])


[20 30]


In [12]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0,2:4])

[30 40]


In [14]:
arr = np.array([[10,20,30,40],[50,60,70,80],[20,30,40,50]])
print(arr[0:2,0:2])

[[10 20]
 [50 60]]


In [15]:
arr = np.array([[10,20,30,40],[50,60,70,80]])
print(arr[0:2,0:2])
print(np.shape(arr))

[[10 20]
 [50 60]]
(2, 4)


In [16]:
print(np.size(arr))

8


In [17]:
print(np.ndim(arr))

2


In [18]:
print(arr.dtype)

int64
