In [2]:
import numpy as np
var1 = np.array([7,6,4,8,9,1,2,3,4])
print(np.sort(var1))

[1 2 3 4 4 6 7 8 9]


In [4]:
a = np.array([[2,5,4,3],[9,7,8,6]])
print(np.sort(var1))

[1 2 3 4 4 6 7 8 9]


In [7]:
var2 = np.array([7,6,4,8,9,1,2,3,4])
s = np.where(var2 == 4)#Search
print(s)

(array([2, 8]),)


In [9]:
print(np.where(var2 % 2==0))

(array([1, 2, 3, 6, 8]),)


In [11]:
var2 = np.array([1,2,3,4])
ss = np.searchsorted(var2,3)
print(ss)


2


In [17]:
a = (np.array([2,5,4,3]))
fa = [True,False,True,False]
new =a[fa]
print(new)

[2 4]
