In [1]:
#Array filled with 0's
#Array filled with 1's
#Create an empty array
#An array with a range of element
#Array diagonal element filled 1's
#Create an array eith values that are spaced linearly in a specified interval

In [2]:
import numpy as np

In [3]:
#######.   ZERO. #########

In [4]:
ar_zero = np.zeros(4)
print(ar_zero)

[0. 0. 0. 0.]


In [8]:

ar_zero1= np.zeros((3,4))
print(ar_zero1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
######## ONES #######

In [10]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [11]:
###### EMPTY #####

In [12]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


In [13]:
####### RANGE #######

In [14]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [15]:
########## DIAGONAL ######

In [16]:
ar_dia = np.eye(3)
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
ar_dia = np.eye(3,5)
print(ar_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [18]:
####### LINE SPACE FUNCTION (linespace) #####

In [21]:
ar_lin = np.linspace(0,20,num=5)
print(ar_lin)

[ 0.  5. 10. 15. 20.]
